# Generated by Django 5.2.4 on 2025-07-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_blocks/'),
        ),
        migrations.AlterField(
            model_name='blogblock',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
