# Generated by Django 5.2.4 on 2025-08-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_topic_blog_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='topics',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AddField(
            model_name='blog',
            name='topics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
